<a href="https://colab.research.google.com/github/GPeyB/COMPUTACION2/blob/main/GJ_OOP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

class GaussJordan:
  def __init__(self,r,c):
    self.renglones = r
    self.columnas = c    
    
  def primeraColumna (self,A,I):
    denf = 0 ## para índices de "diagonal de enfoque"
    denfScaler = 1. /A[denf][denf] # Para hacer el elemento 1 y manejarlo como pivote
    n = len (A)
    for j in range (n): # j = ciclado en columnas
      A[denf][j] = denfScaler * A [denf][j]
      I[denf][j] = denfScaler * A [denf][j]
    print ()
    #imprimirMatrices('', 'A Matrix', A, 'I Matrix', I)

    # Ahora opero sobre los elementos debajo del pivote 
    n = len(A) 
    indices = list(range(n)) # Lista para iterar del tAaño de A

    for i in indices [0:denf] + indices[denf+1:]:
      raScaler = A[i][denf] # ra : renglón actual
      for j in range (n): # ra-raScaler * denfrenglon, un elemento a la vez
        A[i][j] = A[i][j] - raScaler * A[denf][j]
        I[i][j] = I[i][j] - raScaler * I[denf][j]

   # imprimirMatrices('', 'A Matrix', A, 'I Matrix', I)


  def eliminacionCompleta(self,A,I):

    n = len(A)
    indices = list(range(n)) # Para permitir referenciado flexible de renglones
    for denf in range (1,n): # denf (focus diagonal)
      denfScaler = 1.0 / A[denf][denf]
      # Primero ajustAos el renglon con el pivote usando la inversa del pivote
      for j in range (n): #j: ciclado en columnas
        A[denf][j] *= denfScaler
        I[denf][j] *= denfScaler

      # Seccion para imprimir acciones actuales
      string1 = '\nAplicando GJ '
      string2 = ' '
      stringsum = string1 + string2
      val1 = denf+1; val2 = denf+1
      Action = stringsum.format(val1,val2,round(1./denfScaler,3))
      #imprimirMatrices(Action, 'A Matrix', A, 'I Matrix', I)
      print()

      # Operar en cada renglon excepto la de denf
      for i in indices [:denf] + indices [denf+1:]: # Brinca el renglon con pivote
        raScaler = A[i][denf]
        for j in range (n):
          A[i][j] = A[i][j] -raScaler * A[denf][j]
          I[i][j] = I[i][j] -raScaler * I[denf][j]
      
      # Sección para imprimir acciones actuales

    string1 = 'Obtenemos la identidad del lado izquierdo'
    string2 = ' y la inversa del lado derecho \n'
    val1 = i+1; val2 = denf+1
    stringsum = string1 + string2
    Action = stringsum.format(raScaler, val2, val1, raScaler, val2, val1)
    imprimirMatrices(Action, 'A Matrix', A, 'I Matrix', I)
    print()


In [ ]:
def imprimirMatrices(Action, Title1, M1, Title2, M2):
    print (Action)
    print (Title1, '\t' *int(len(M1)/2)+'\t' * len(M1), Title2)
    for i in range(len(M1)):
      row1 = ['{0:+7.3f}'.format(x) for x in M1[i]]
      row2 = ['{0:+7.3f}'.format(x) for x in M2[i]]
      print(row1,'\t', row2)  

def main():

    # Definición de número de filas y columnas
    r = 3
    c = 3
  
    # Inicializar una matriz 
    A = np.random.randint(1,10, (r,c))
    I = np.identity(len(A))
    #A = [[5.,3.,1.],[3.,9.,4.],[1.,3.,5.]]
    #I = [[1.,0.,0.],[0.,1.,0.],[0.,0.,1.]]

    print("matrix aleatoria:\n", A)
    
    # Creación de un objeto
    objG = GaussJordan(r,c)
    objG.primeraColumna(A,I)
    objG.eliminacionCompleta(A,I)


if __name__ == "__main__":
    main()

matrix aleatoria:
 [[6 6 5]
 [5 1 4]
 [7 9 1]]



Obtenemos la identidad del lado izquierdo y la inversa del lado derecho 

A Matrix 				 I Matrix
[' +1.000', ' +0.000', ' +0.000'] 	 [' +0.486', ' +0.569', ' -0.333']
[' +0.000', ' +1.000', ' +0.000'] 	 [' -0.319', ' -0.403', ' +0.333']
[' +0.000', ' +0.000', ' +1.000'] 	 [' -0.528', ' -0.361', ' +0.333']

